/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "adminprimary": "#c21e2f",
                "primary": "var(--primary, #c21e2f)",
                "primary-fixed": "var(--primary-fixed, #fde8e9)",
                "primary-fixed-dim": "var(--primary-fixed-dim, #fca5a5)",
                "primary-container": "var(--primary-container, #fde8e9)",
                "on-primary-container": "var(--on-primary-container, #7f1d1d)",
                "on-primary-fixed-variant": "var(--on-primary-fixed-variant, #9f1239)",
                "secondary": "var(--secondary, #f43f5e)",
                "secondary-fixed": "var(--secondary-fixed, #ffedd5)",
                "secondary-fixed-dim": "var(--secondary-fixed-dim, #fdba74)",
                "secondary-container": "var(--secondary-container, #fff1f2)",
                "on-secondary-container": "var(--on-secondary-container, #4c0519)",
                "tertiary": "var(--tertiary, #fb923c)",
                "tertiary-fixed": "var(--tertiary-fixed, #ffedd5)",
                "tertiary-fixed-dim": "var(--tertiary-fixed-dim, #fdba74)",
                "tertiary-container": "var(--tertiary-container, #fff7ed)",
                "on-tertiary-container": "var(--on-tertiary-container, #7c2d12)",
                "surface": "var(--surface, #f8f6f6)",
                "surface-dim": "var(--surface-dim, #f1ecf0)",
                "surface-bright": "var(--surface-bright, #ffffff)",
                "surface-variant": "var(--surface-variant, #f1f5f9)",
                "on-surface": "var(--on-surface, #334155)",
                "on-surface-variant": "var(--on-surface-variant, #64748b)",
                "surface-container-lowest": "var(--surface-container-lowest, #ffffff)",
                "surface-container-low": "var(--surface-container-low, #f8fafc)",
                "surface-container": "var(--surface-container, #f1f5f9)",
                "surface-container-high": "var(--surface-container-high, #e2e8f0)",
                "surface-container-highest": "var(--surface-container-highest, #cbd5e1)",
                "outline-variant": "var(--outline-variant, #e2e8f0)",
                "on-background": "var(--on-background, #0f172a)",
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans", "Meiryo", "sans-serif"],
                "display": ["Plus Jakarta Sans", "Meiryo", "sans-serif"],
                "body": ["Work Sans", "Meiryo", "sans-serif"],
            },
        },
    },
    plugins: [],
}
